services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h db -p 1221"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy



volumes:
  postgres_data:

